name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get package info
        id: package_info
        run: |
          version=$(grep "PACKAGE_VERSION =" Makefile | cut -d' ' -f3)

          if [ -z "$version" ]; then
            version=$(grep "Version:" control | cut -d' ' -f2)
          fi

          echo "id=$(grep "Package:" control | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rsync

      - name: Setup theos
        uses: level3tjg/theos-action@main
        with:
          cache: true
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Set Debug Variables
        id: debug_vars
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Building on main: Debug Menu OFF"
            echo "cflags=-DREDDITFILTER_DEBUG=0" >> "$GITHUB_OUTPUT"
          else
            echo "Building on ${{ github.ref_name }}: Debug Menu ON"
            echo "cflags=-DREDDITFILTER_DEBUG=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Build rootless deb
        run: make package
        env:
          FINALPACKAGE: 1
          THEOS_PACKAGE_SCHEME: rootless
          ADDITIONAL_CFLAGS: ${{ steps.debug_vars.outputs.cflags }}

      - name: Build rootful deb
        run: make clean package
        env:
          FINALPACKAGE: 1
          ADDITIONAL_CFLAGS: ${{ steps.debug_vars.outputs.cflags }}

      - name: List packages
        run: |
          echo "Built packages:"
          ls -lh packages/

      - name: Hash release files
        id: hash_files
        run: |
          echo 'hashes<<EOF' >> "$GITHUB_OUTPUT"
          sha256sum packages/*.deb >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

      - name: Create release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: packages/*.deb
          tag_name: v${{ steps.package_info.outputs.version }}
          body: |
            ## SHA256

            ${{ steps.hash_files.outputs.hashes }}
